---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: ubuntu
 
verifier:
  name: terraform
  systems:
    - name: default
      attrs_outputs:
        terraform_tags: instance_id
      backend: local
      controls:
      - check_string

suites:
  - name: default
